version: '3'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app

    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./src:/var/app/src
